name: clean_archit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.6.7
  intl: ^0.19.0
  floor: ^1.4.0
  retrofit: ^4.1.0
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.3.1
  analyzer: ^5.13.0
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.1.1
  floor_generator: ^1.4.2
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  fonts:
    - family: Multi
      fonts:
        - asset: assets/fonts/multi/MultiDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/multi/MultiDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/multi/MultiDisplay-Regular.otf
